# Generated by Django 5.1.2 on 2024-11-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('ta_id', models.IntegerField(blank=True, null=True)),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('query', models.CharField(blank=True, max_length=50, null=True)),
                ('ans', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_table',
                'managed': False,
            },
        ),
    ]
