# Generated by Django 5.1.2 on 2024-11-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_mytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoubtTable',
            fields=[
                ('course_id', models.CharField(max_length=4)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('ans', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doubt_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyTable',
            fields=[
                ('faculty_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'faculty_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'student_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaTable',
            fields=[
                ('ta_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=4)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ta_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_table',
                'managed': False,
            },
        ),
    ]
