# Generated by Django 5.1.2 on 2024-11-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_maintable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
