# Generated by Django 5.1.2 on 2025-01-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_topicstable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='CommentTable',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DoubtTable',
        ),
        migrations.DeleteModel(
            name='FacultyTable',
        ),
        migrations.DeleteModel(
            name='MainTable',
        ),
        migrations.DeleteModel(
            name='MyTable',
        ),
        migrations.DeleteModel(
            name='StudentTable',
        ),
        migrations.DeleteModel(
            name='TaTable',
        ),
        migrations.DeleteModel(
            name='TopicsTable',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
