# Generated by Django 5.1.3 on 2025-01-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_coursetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetable',
            options={'managed': True},
        ),
    ]
