# Generated by Django 5.1.3 on 2025-01-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_coursetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetable',
            options={'managed': False},
        ),
    ]
